

###

POST http://localhost:4000/articles HTTP/1.1
Content-Type: application/json

{
	"name": "converses",
	"image": "",
	"price": 2000,
	"description": "maison exterieur",
	"categories": [""]
	
}

###

GET http://localhost:4000/articles/60dc26ffb57fd144906be6c9

###
# DELETE USER
DELETE http://localhost:4000/articles/60dc26ffb57fd144906be6c9

###

PATCH http://localhost:4000/articles/60dc2205b57fd144906be6c8
Content-Type: application/json

{
	"name": "chausson",
	"image": "",
	"price": 500,
	"description": "été/hiver/printemps",
	"categories": [""]
}


###

POST http://localhost:4000/users HTTP/1.1
Content-Type: application/json

{
	"email": "samy@mail.com",
	"password": "test123",
	"username": "samy",
	"firstname": "antoine",
	"lastname": "samy",
	"age": 20
	
}

###

GET http://localhost:4000/users/60dc5dd4831a95592c05ba1b

###

DELETE http://localhost:4000/users/60dc5dd4831a95592c05ba1b

###

PATCH http://localhost:4000/users/60dc64e7620d6c2374519103
Content-Type: application/json

{
	"email": "samy@mail.com",
	"password": "test123",
	"username": "samy",
	"firstname": "antoine",
	"lastname": "samy",
	"age": 30
	
}

###

POST http://localhost:4000/login HTTP/1.1
Content-Type: application/json

{
	"email": "samy@mail.com",
	"password":"test123"
	
}