

###

POST http://localhost:3000/articles HTTP/1.1
Content-Type: application/json

{
	"name": "Saumon grillé",
	"image": "img/food/foodiesfeed.com_grilled-salmon-cubes-with-vegetables (Small).jpg",
	"price": 1850,
	"description": "Saumon grillé sur som lit de légumes méditerranéen",
	"categories": ["spicy"],
	"popular": false
}